import { useState } from 'react'
import { createRoot } from 'react-dom/client'
import './styles.css'

const projects = [
  ['TrustFlow Bank','Fintech Web App','React · Node.js · PostgreSQL'],['PureLife+ Hospital','Healthcare Website','React · JavaScript'],['Atlas International Airport','Institutional Platform','React · Node.js'],['Hospital Management System','Healthcare Web App','React · PostgreSQL'],['LagosHomes','Real Estate','React · JavaScript'],['NaijaHomes','Real Estate · AI-assisted','Base44 · React'],['MARVEAUX Digital Studio','Agency Website','React · 3D Animation'],['Pinnacle University','Academic Platform','React · Node.js'],['Still Life Home','Furniture E-Commerce','React · Tailwind'],['VYBN Fashion Store','Fashion E-Commerce','React · JavaScript'],['Glows Beauty','Booking Site','React · JavaScript'],['Kartify','E-Commerce','React · Node.js'],['KITAN Digital Studio','Personal Brand Site','React · Node.js'],['Glam by Mira','Booking Site','React · Bolt'],['CleanPro','Booking Site','React · Bolt'],['FixIt','Booking Site','React · JavaScript'],['EatWell','Subscription Site','React · JavaScript'],['ZenSpace','Membership Platform','React · Bolt'],['Velvet & Vine','Salon & Spa Booking','Bolt.new · React'],['EventCraft','Events Platform','React · JavaScript'],['Leo Digital Studio','Art Studio Site','React · JavaScript'],['SkyCast','Weather PWA','React · Vite · Open-Meteo'],['Built By Naija','Tribute Page','HTML · CSS · JavaScript'],['Etched in Stone','Editorial Site','HTML · CSS · JavaScript']
]

const services = ['Full-Stack Development','UI/UX Design','Brand Strategy','Copywriting & Content Strategy','Prompt Engineering & AI Workflow Integration','No-Code / AI-Assisted Builds']
const faqs = ['What services does MARVEAUX Digital Studio offer?','Do you offer branding strategy or only UI design?','How does the process work from idea to delivery?','Do you offer support after launch?','What is your turnaround time?','Do you work with international clients?']

function App() {
  const [openFaq, setOpenFaq] = useState(null)
  const [sent, setSent] = useState(false)
  const submit = event => { event.preventDefault(); setSent(true) }

  return <div className="site">
    <header className="nav"><a className="logo" href="#home">MARVEAUX<span>✦</span></a><nav>{['About','Services','Portfolio','Pricing','FAQ','Contact'].map(item => <a key={item} href={`#${item.toLowerCase()}`}>{item}</a>)}</nav><a className="button small" href="#contact">Let's Talk ↗</a></header>
    <main>
      <section id="home" className="hero"><p className="eyebrow">MARVEAUX DIGITAL STUDIO</p><h1>We build <i>digital</i> experiences that <i>elevate</i> brands.</h1><p className="lead">Modern websites, strategic branding, motion graphics, and high-converting digital experiences — designed and shipped end to end.</p><div className="actions"><a className="button" href="#portfolio">View Portfolio ↗</a><a className="button ghost" href="#contact">Start Your Project</a></div><div className="stats"><span><b>24+</b>Projects</span><span><b>10+</b>Industries</span><span><b>3</b>Years</span><span><b>#2</b>Wattpad Purity</span></div></section>
      <section id="about" className="section about"><div><p className="eyebrow">ABOUT</p><h2>One person.<br/><i>Every skill</i> you need.</h2></div><div className="copy"><p>I architect and ship full-stack products — frontend, backend, database, deployment, brand, and copy — end to end, alone, at a level most people need a four-person team for.</p><p>24+ live, production-deployed builds across fintech, healthcare, real estate, hospitality, fashion, education, and beauty. I direct AI coding agents the way a lead engineer directs a junior developer: detailed spec, generated output, audit, fix, ship.</p><p>Anthropic-certified in prompt engineering. Published fiction author ranked #2 on Wattpad. Final-year B.Tech student at FUTA.</p></div></section>
      <section id="services" className="section"><p className="eyebrow">SERVICES</p><h2>Everything a brand needs,<br/><i>under one roof.</i></h2><div className="service-grid">{services.map((service, i) => <article className="card" key={service}><span className="number">0{i+1}</span><h3>{service}</h3><p>Thoughtful strategy and polished execution shaped around your next meaningful step.</p></article>)}</div></section>
      <section id="portfolio" className="section"><p className="eyebrow">SELECTED WORK</p><h2>Across <i>ten industries.</i></h2><div className="project-grid">{projects.map(([name, category, stack], i) => <article className="project" key={name}><div className="project-image"><span>{String(i+1).padStart(2,'0')}</span></div><p className="tag">{category}</p><h3>{name}</h3><small>{stack}</small>{name === 'SkyCast' && <a className="live" href="https://skycast-weather-neon.vercel.app/" target="_blank" rel="noreferrer">Live ↗</a>}</article>)}</div></section>
      <section id="pricing" className="section"><p className="eyebrow">PRICING</p><h2>Three ways to <i>work together.</i></h2><div className="price-grid">{[['Starter','Foundation','A sharp, fast marketing site that earns trust on first load.'],['Growth','Momentum','Site, identity and messaging built as one coherent system.'],['Full-Service','Everything','A complete product build with AI woven into the workflow.']].map(([name, sub, text], i) => <article className={`card price ${i===1?'featured':''}`} key={name}>{i===1&&<b className="recommended">RECOMMENDED</b>}<p className="eyebrow">{sub}</p><h3>{name}</h3><p>{text}</p><hr/><p>Contact for pricing</p><a className="button ghost" href="#contact">Let's discuss ↗</a></article>)}</div></section>
      <section id="faq" className="section faq"><p className="eyebrow">FAQ</p><h2>Questions, answered <i>plainly.</i></h2>{faqs.map((question, i) => <div className="faq-row" key={question}><button onClick={() => setOpenFaq(openFaq === i ? null : i)} aria-expanded={openFaq === i}>{question}<span>{openFaq === i ? '−' : '+'}</span></button>{openFaq === i && <p>Yes. We clarify the goal, shape the scope, design and build the solution, then test and ship it with you.</p>}</div>)}</section>
      <section id="contact" className="section contact"><div><p className="eyebrow">CONTACT</p><h2>Tell me what<br/>you’re <i>building.</i></h2><p className="lead">Remote-first, working with clients worldwide. Every enquiry gets a direct reply.</p><div className="contact-links"><a href="mailto:aloemmanuel369@gmail.com">aloemmanuel369@gmail.com</a><a href="https://github.com/aloemmanuel369-hue">GitHub ↗</a><a href="https://linkedin.com/in/alo-emmanuel">LinkedIn ↗</a><a href="tel:08101075489">0810 107 5489</a></div></div><form className="contact-form" onSubmit={submit}><input required placeholder="Your name" aria-label="Your name"/><input required type="email" placeholder="Your email" aria-label="Your email"/><select aria-label="Project type" defaultValue=""><option value="" disabled>Project type</option><option>Website</option><option>Brand strategy</option><option>Full product</option><option>Something else</option></select><textarea required rows="5" placeholder="Tell me what you're building..." aria-label="Project message"/><button className="button" type="submit">{sent ? 'Message ready ✓' : 'Send Message ↗'}</button>{sent && <p className="success">Thanks — your message has been received. Connect the `/api/contact` endpoint for email delivery.</p>}</form></section>
    </main><footer><b>MARVEAUX</b><span>DESIGN. DEVELOP. ELEVATE.</span><span>© 2026 MARVEAUX Digital Studio.</span></footer>
  </div>
}

createRoot(document.getElementById('root')).render(<App />)
